version: 1
disable_existing_loggers: False

formatters:
    json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
        format: "%(asctime)s %(name)s %(levelname)s %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: json
        filename: /var/log/krakend-updater/service.log
        maxBytes: 10485760
        backupCount: 5

loggers:
    krakend_updater:
        level: INFO
        handlers: [console, file]
        propagate: no

root:
    level: INFO
    handlers: [console]
