name: Krakend Deployment Pipeline
on:
  workflow_dispatch:
    inputs:
      updated_service_name:
        description: The updated service name
        required: true
        default: none
      updated_service_port:
        description: The updated service port
        required: true
        default: "8080"
  push:
    branches:
      - main

jobs:
  generate-validate-push-config:
    name: "Generate, Validate, Push Config"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Receive inputs
        run: |
          echo "Updated Service: ${{ github.event.inputs.updated_service_name }}"
          echo "Swagger File: ${{ github.event.inputs.updated_service_name }}:${{ github.event.inputs.updated_service_port }}/v3/api-docs"
      - name: Generate Krakend Config
        working-directory: ./scripts
        run: |
          chmod +x ./convert.sh
          ./convert.sh -f "${{ github.event.inputs.updated_service_name }}:${{ github.event.inputs.updated_service_port }}/api-docs.yaml" -o settings/${{ github.event.inputs.updated_service_name }}.json
      # Krakend will validate in portainer
      # - name: Validate Krakend Configuration
      #   run: |
      #     if [ -f "${{ github.event.inputs.updated_service_name }}.json" ]; then
      #       docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace devopsfaith/krakend check -c ${{ github.event.inputs.updated_service_name }}.json
      #     else
      #       echo "Configuration file not found: ${{ github.event.inputs.updated_service_name }}.json"
      #       exit 1
      #     fi
      - name: Commit and Push Config to KrakenD Repo
        env:
          GHX_TOKEN: ${{ secrets.GHX_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout -b update-krakend-config-${{ github.event.inputs.updated_service_name }}
          git add scripts/settings/${{ github.event.inputs.updated_service_name }}.json
          git commit -m "Update KrakenD config based on Swagger API for ${{github.event.inputs.updated_service_name }}"
          git push https://x-access-token:${{ secrets.GHX_TOKEN }}@github.com/testmate-app/krakend.git update-krakend-config-api.mate.institute

  trigger-redeploy:
    name: Trigger Redeployment Webhook
    runs-on: ubuntu-latest
    needs: generate-validate-push-config
    if: "${{ success() }}"
    steps:
      - name: Trigger Portainer Webhook for Redeployment
        run: |
          curl --insecure -X POST ${{ secrets.WEB_HOOK }}
