name: Krakend Deployment Pipeline
on:
  workflow_dispatch:
    inputs:
      updated_service_name:
        description: The updated service name
        required: true
        default: none
      updated_service_port:
        description: The updated service port
        required: true
        default: "8080"

jobs:
  generate-validate-push-config:
    name: "Generate, Validate, Push Config"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH
        run: |
          ssh-add -l
          ls -la ~/.ssh
          echo "Testing SSH connection to GitHub..."
          ssh -T git@github.com -v

      - name: Setup Git Config
        run: |
          git config --global user.name "fikihfirmansyah"
          git config --global user.email "fikihfirmansyah43@gmail.com"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Commit and Push Config
        run: |
          # Check if branch exists
          if git show-ref --verify --quiet "refs/heads/update-krakend-config-api.mate.institute"; then
            git checkout "update-krakend-config-api.mate.institute"
          else
            git checkout -b "update-krakend-config-api.mate.institute"
          fi

          git remote set-url origin git@github.com:testmate-app/krakend.git

          if git add scripts/settings/api.mate.institute.json; then
            git commit -m "Update KrakenD config based on Swagger API for api.mate.institute"
            GIT_SSH_COMMAND='ssh -v' git push origin "update-krakend-config-api.mate.institute"
          else
            echo "No changes to commit"
            exit 0
          fi
